# Starship prompt configuration
# https://starship.rs/config/

# Minimal, fast prompt
add_newline = false
format = "$username$hostname$directory$git_branch$git_status$character"

# Timeout for command execution
command_timeout = 500

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[directory]
truncation_length = 3
truncate_to_repo = true
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "on [$symbol$branch]($style) "
symbol = " "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
conflicted = "="
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?${count}"
stashed = "$${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"

[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = false

[hostname]
ssh_only = true
format = "@ [$hostname](bold blue) "
disabled = false

# Language-specific modules
[nodejs]
format = "via [ $version](bold green) "

[python]
format = "via [ $version](yellow) "

[rust]
format = "via [ $version](red) "

[golang]
format = "via [ $version](cyan) "

# Execution time
[cmd_duration]
min_time = 2_000
format = "took [$duration]($style) "
